# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74ef87d93ed14a4a7465b66a1fa2dc2bde1995eded7497c372645d717e5f7a807dc3ad343155983e1dac1a236314ee54b3f6e2d2072cc9623d1b4dc196b53fbb

test:
  secret_key_base: 893ba3d4f41d5cb7b34ef3d46880c51936eb33e4b4b0e7918ab79ca2f6b4bbb1936565d4082b74ded02415cf10aeca7b62b05c52c1f6b9051995f7c8bab7feeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
